spring:
  application:
    name: sleuth-article
  zipkin:
    # base-url: http://127.0.0.1:9411
    sender:
      # 修改zikpin的数据发送方式为RabbitMq
      type: RABBIT
  sleuth:
    sampler:
      # zikpin抽样比例 默认0.1
      probability: 1.0
  # rabbitmq配置
  rabbitmq:
    addresses: amqp://127.0.0.1:5672
    username: ll
    password: 123456
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://ll:123456@127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true